entrenamientos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_rutinas, name='lista_rutinas'),
    path('crear/', views.crear_rutina, name='crear_rutina'),
       path('rutina/<int:rutina_id>/', views.detalle_rutina, name='detalle_rutina'),

       path('editar/<int:rutina_id>/', views.editar_rutina, name='editar_rutina'),
path('eliminar/<int:rutina_id>/', views.eliminar_rutina, name='eliminar_rutina'),
]

fitplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entrenamientos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

entrenamientos/models.py
from django.db import models
from django.contrib.auth.models import User

class Rutina(models.Model):

    TIPO_CHOICES = [
        ('cardio', 'Cardio'),
        ('fuerza', 'Fuerza'),
        ('hipertrofia', 'Hipertrofia'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50, choices=TIPO_CHOICES)
    descripcion = models.TextField()


    imagen = models.ImageField(
        upload_to='rutinas/',
        null=True,
        blank=True
    )

    creada = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

entrenamientos/forms.py
from django import forms
from .models import Rutina


class RutinaForm(forms.ModelForm):
    class Meta:
        model = Rutina
        exclude = ['usuario']

        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'input',
                'placeholder': 'Nombre de la rutina'
            }),

            'tipo': forms.Select(attrs={
                'class': 'input'
            }),

            'descripcion': forms.Textarea(attrs={
                'class': 'input',
                'rows': 4,
                'placeholder': 'Describe la rutina'
            }),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()

    return render(request, 'registration/signup.html', {'form': form})

entrenamientos/views.py
from django.shortcuts import render, redirect
from .models import Rutina
from .forms import RutinaForm
from django.contrib.auth.decorators import login_required

@login_required
def lista_rutinas(request):
    rutinas = Rutina.objects.filter(usuario=request.user)
    return render(request, 'entrenamientos/lista_rutinas.html', {'rutinas': rutinas}
    )

@login_required
def crear_rutina(request):
    if request.method == 'POST':
        form = RutinaForm(request.POST, request.FILES)

        if form.is_valid():
            rutina = form.save(commit=False)
            rutina.usuario = request.user
            rutina.save()
            return redirect('lista_rutinas')

    else:
        form = RutinaForm()

    return render(request, 'entrenamientos/crear_rutina.html', {
        'form': form
    })
def detalle_rutina(request, rutina_id):
    rutina = Rutina.objects.get(id=rutina_id)

    return render(request, 'entrenamientos/detalle_rutina.html', {
        'rutina': rutina
    })
@login_required
def editar_rutina(request, rutina_id):
    rutina = Rutina.objects.get(id=rutina_id)

    if request.method == 'POST':
        form = RutinaForm(request.POST, request.FILES, instance=rutina)

        if form.is_valid():
            form.save()
            return redirect('lista_rutinas')

    else:
        form = RutinaForm(instance=rutina)

    return render(request, 'entrenamientos/editar_rutina.html', {
        'form': form
    })
@login_required
def eliminar_rutina(request, rutina_id):
    rutina = Rutina.objects.get(id=rutina_id)

    if request.method == 'POST':
        rutina.delete()
        return redirect('lista_rutinas')

    return render(request, 'entrenamientos/eliminar_rutina.html', {
        'rutina': rutina
    })

entrenamientos/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>TrainSystem</title>

    <!-- CSS PRINCIPAL -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>

<!-- NAVBAR -->
<nav class="navbar">

    <div class="nav-logo">
        TrainSystem
    </div>

    <div class="nav-links">
        {% if user.is_authenticated %}
            <span>Hola {{ user.username }}</span>

            <a href="{% url 'lista_rutinas' %}">Rutinas</a>
            <a href="{% url 'crear_rutina' %}">Crear Rutina</a>
            <a href="{% url 'logout' %}" class="logout-btn">Cerrar sesión</a>

        {% else %}
            <a href="{% url 'login' %}" class="login-btn">Login</a>
        {% endif %}
    </div>

</nav>

<!-- CONTENIDO -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

entrenamientos/templates/entrenamientos/crear_rutina.html
{% extends "base.html" %}

{% block content %}

<div class="form-container">

    <h2>Crear Nueva Rutina</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-fields">
            {{ form.as_p }}
        </div>

        <button type="submit" class="btn-primary">
            Guardar Rutina
        </button>

        <a href="{% url 'lista_rutinas' %}" class="btn-secondary">
            Cancelar
        </a>

    </form>

</div>

{% endblock %}

entrenamientos/templates/entrenamientos/detalle_rutina.html
{% extends "base.html" %}

{% block content %}

<div class="detalle-container">

    <h1 class="titulo-seccion">{{ rutina.nombre }}</h1>

    <p class="detalle-tipo">
        Tipo: {{ rutina.tipo }}
    </p>

    <!-- IMAGEN SI EXISTE -->
    {% if rutina.imagen %}
        <div class="detalle-img-box">
            <img src="{{ rutina.imagen.url }}" alt="Imagen rutina">
        </div>
    {% endif %}

    <p class="detalle-descripcion">
        {{ rutina.descripcion }}
    </p>

    <div class="detalle-botones">

        <a href="{% url 'editar_rutina' rutina.id %}" class="btn-editar">
            Editar
        </a>

        <a href="{% url 'eliminar_rutina' rutina.id %}" class="btn-eliminar">
            Eliminar
        </a>

        <a href="{% url 'lista_rutinas' %}" class="btn-ver">
            Volver
        </a>

    </div>

</div>

{% endblock %}

entrenamientos/templates/entrenamientos/editar_rutina.html
{% extends "base.html" %}

{% block content %}

<div class="card-premium">
    <h2>Editar Rutina</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn-primary">
            Guardar Cambios
        </button>
    </form>
</div>

{% endblock %}

entrenamientos/templates/entrenamientos/eliminar_rutina.html
{% extends 'base.html' %}

{% block content %}

<div class="delete-card">

    <h2>Eliminar Rutina</h2>

    <p>
        ¿Seguro que quieres eliminar
        <strong>{{ rutina.nombre }}</strong>?
    </p>

    <form method="POST">
        {% csrf_token %}

        <div class="delete-actions">
            <button type="submit" class="btn-eliminar">
                Sí, eliminar
            </button>

            <a href="{% url 'lista_rutinas' %}" class="btn-secondary">
                Cancelar
            </a>
        </div>

    </form>

</div>

{% endblock %}

entrenamientos/templates/entrenamientos/lista_rutinas.html
{% extends "base.html" %}

{% block content %}

<h1 class="titulo-seccion">Mis Rutinas</h1>

<div class="rutinas-grid">

    {% for rutina in rutinas %}
    <div class="rutina-card">

        <h2>{{ rutina.nombre }}</h2>

        <p class="tipo">
            {{ rutina.get_tipo_display }}
        </p>

        <p class="descripcion">
            {{ rutina.descripcion|truncatechars:120 }}
        </p>

        <div class="card-botones">
            <a href="{% url 'detalle_rutina' rutina.id %}" class="btn-ver">
                Ver
            </a>

            <a href="{% url 'editar_rutina' rutina.id %}" class="btn-editar">
                Editar
            </a>

            <a href="{% url 'eliminar_rutina' rutina.id %}" class="btn-eliminar">
                Eliminar
            </a>
        </div>

    </div>
    {% endfor %}

</div>

{% endblock %}